Repository nextreleaseio/next-release, pull requests merged in 2020-06, with the labels that each got.

#128 Add blog post explaining screw up
  content/blog/2020-06-01-big-indentation-screw-up.md
Labels: content

#130 Added blog post about github permissions
  .github/workflows/changelog.yml
  content/blog/2020-06-15-new-permissions.md
  src/images/blog/security.png
Labels: content

#132 Commitment to End Systemic Racism Post
  content/blog/commitment-to-end-systemic-racism.md
Labels: enhancement

#134 Adding DevOps Org Metrics Post
  content/blog/your-teams-devops-stats.md
Labels: enhancement

#136 Fixing styling of video
  content/blog/your-teams-devops-stats.md
Labels: bug

#138 Adding Project DevOps Metric blog post
  content/blog/project-devops-stats.md
Labels: enhancement

#140 Grammarly continuing to pwn me
  content/blog/project-devops-stats.md
Labels: enhancement

#141 Updating publish date on project performance post
  content/blog/project-devops-stats.md
Labels: bug

#143 Django REST Framework Sponsorship Post
  content/blog/django-rest-framework-sponsorship.md
Labels: enhancement

#145 Updating subtitle
  content/blog/django-rest-framework-sponsorship.md
Labels: enhancement

#147 Fixing url path
  content/blog/django-rest-framework-sponsorship.md
  content/blog/project-devops-stats.md
Labels: bug

#146 Fixed typo on permission publish date
  content/blog/2020-06-15-new-permissions.md
Labels: bug

#149 Google Authentication Blog Post
  content/blog/google-sso-authentication.md
Labels: enhancement
