Repository nextreleaseio/next-release, pull requests merged in 2020-04, with the labels that each got.

#55 Performance Notes Service Offering
  .nvmrc
  CHANGELOG.md
  content/performance_notes/health_report.md
  content/performance_notes/metrics.md
  content/performance_notes/showcase.md
  content/performance_notes/stakeholders.md
  gatsby-config.js
  gatsby-node.js
  package.json
  src/components/header.js
  src/images/performance_notes/health_check.png
  src/images/performance_notes/metrics_analysis.png
  src/images/performance_notes/teamwork.png
  src/images/performance_notes/video_workspace.png
  src/pages/performance_notes.js
  src/templates/performance_notes.js
  yarn.lock
Labels: enhancement

#57 Release Branch Strategies Blog Post
  content/blog/release_strategies.md
  content/performance_notes/showcase.md
  gatsby-node.js
  src/images/kb/workflow_gitflow.png
  src/images/kb/workflow_single branch.png
  src/images/kb/workflow_staging and production.png
Labels: enhancement

#59 Automating Your Release Notes Blog Post + Other Enhancements
  content/blog/automate_your_release_notes.md
  content/blog/getting_started_with_devops.md
  content/blog/github-issue.md
  content/blog/release_strategies.md
  content/performance_notes/health_report.md
  content/performance_notes/metrics.md
  content/performance_notes/showcase.md
  content/performance_notes/stakeholders.md
  src/pages/performance_notes.js
  src/templates/performance_notes.js
Labels: enhancement

#61 DevOps Post Edits
  content/blog/getting_started_with_devops.md
Labels: enhancement

#63 Fixing minor styling issues (hopefully)
  package.json
  src/components/footer.js
  src/components/layout.js
  src/pages/automatic-release-notes.js
  src/pages/index.js
  src/templates/blog.js
  src/templates/kb.js
  src/templates/performance_notes.js
  src/templates/product.js
  yarn.lock
Labels: bug

#65 Fixing missing testimonial content
  .gitignore
  content/testimonials/tyler-esg.md
  package.json
  src/components/loom.js
  src/pages/index.js
Labels: bug

#67 Release Orchestration Article
  CHANGELOG.md
  content/blog/getting_started_with_devops.md
  content/blog/release_orchestration.md
  yarn.lock
Labels: enhancement

#70 Added unsubscribe page
  src/components/location.js
  src/pages/unsubscribe.js
  src/pages/welcome.js
  yarn.lock
Labels: enhancement

#71 Advance Release Notices Blog Post
  content/blog/advanced_release_success.md
Labels: enhancement

#73 Adding Profile Pics to Blog List
  content/blog/2020-03-prod-update.md
  content/blog/advance_release_success.md
  content/blog/automate_your_release_notes.md
  content/blog/first-post.md
  content/blog/getting_started_with_devops.md
  content/blog/github-issue.md
  content/blog/release_orchestration.md
  content/blog/release_strategies.md
  src/pages/blog.js
  src/templates/blog.js
Labels: enhancement

#75 Upgrading gatsby to fix build error
  package-lock.json
  package.json
  yarn.lock
Labels: bug

#76 Added new footer
  package.json
  src/components/footer.js
  tailwind.config.js
  yarn.lock
Labels: bug

#77 Improve contact form page
  src/pages/contact.js
Labels: bug

#78 Simplify pricing page
  src/components/footer.js
  src/pages/contact.js
  src/pages/pricing.js
  tailwind.config.js
Labels: bug

#79 Add better blog and help index layouts
  package-lock.json
  src/components/help-card.js
  src/pages/blog.js
  src/pages/help/gettingstarted.js
  src/pages/help/using-next-release.js
Labels: bug

#80 Add New Content For Reports Features
  content/blog/report_announcement.md
  content/product/changes.md
  src/components/header.js
  src/pages/performance_notes.js
  src/pages/pricing.js
  src/templates/product.js
Labels: enhancement

#81 Fix Typo
  src/pages/contact.js
  src/pages/performance_notes.js
Labels: bug

#83 Enhance blog page template
  content/blog/2020-40-23-python-choices-enums.md
  gatsby-browser.js
  gatsby-config.js
  package.json
  src/components/author.js
  src/css/markdown-github.css
  src/images/blog/using-choices.png
  src/images/blog/using-enums.png
  src/images/people/devon.png
  src/images/people/donald.jpg
  src/templates/blog.js
  yarn.lock
Labels: enhancement

#84 Add og image support
  content/blog/2020-03-prod-update.md
  content/blog/2020-40-23-python-choices-enums.md
  src/components/seo.js
  src/templates/blog.js
Labels: enhancement

#86 Add Django Blog Post
  src/images/icons/NextRelease_Color_Stacked.png
Labels: enhancement

#87 Fix media queries on blog page
  src/components/author.js
  src/templates/blog.js
Labels: bug

#89 Fix for the image fix
  src/components/author.js
Labels: bug

#91 Fix for the fix for the fix
  src/components/author.js
Labels: bug

#92 Fixed broken social media images & links
  CHANGELOG.md
  content/blog/advance_release_success.md
  content/blog/automate_your_release_notes.md
  content/blog/first-post.md
  content/blog/getting_started_with_devops.md
  content/blog/github-issue.md
  content/blog/release_orchestration.md
  content/blog/release_strategies.md
  content/blog/report_announcement.md
  src/components/author.js
  src/images/blog/NextRelease_Color_Stacked.png
  src/images/blog/advance_shipping_notice.png
  src/images/blog/automate_release_notes.png
  src/images/blog/devops_team.png
  src/images/blog/release_orchestration.png
  src/images/blog/release_strategies/GitFlowHotfixBranch.png
  src/images/blog/release_strategies/workflow_gitflow.png
  src/images/blog/release_strategies/workflow_single_branch.png
  src/images/blog/release_strategies/workflow_staging_and_production.png
  src/images/blog/reports_showcase.png
Labels: bug

#95 Add Blog Posts and KB articles for reports
  content/blog/2020-04-prod-update-reports.md
  content/kb/manual_emails.md
  content/kb/reports.md
  content/kb/slack.md
  src/images/screenshots/create-report.png
  src/images/screenshots/drafts.png
  src/images/screenshots/inline-email-list.png
  src/images/screenshots/manage-emails.png
  src/images/screenshots/manual-email.png
  src/images/screenshots/release-detail-2020-04-30.png
  src/images/screenshots/release-detail-reports.png
Labels: content

#97 Initial velocity blog draft
  content/blog/advance_release_success.md
  content/blog/automate_your_release_notes.md
  content/blog/getting_started_with_devops.md
  content/blog/release_orchestration.md
  content/blog/release_strategies.md
  content/blog/velocity.md
  src/images/blog/busywork_burnout.png
Labels: enhancement

#99 Update report videos
  content/blog/2020-04-prod-update-reports.md
  content/kb/manual_emails.md
  content/kb/reports.md
  content/product/changes.md
Labels: content
