Repository nextreleaseio/next-release, pull requests merged in 2020-05, with the labels that each got.

#101 add kb article on status checks
  content/kb/adding-status-check.md
  src/images/screenshots/branch-protect.png
  src/images/screenshots/require-branch-rule.png
  src/images/screenshots/status-check.png
Labels: content

#103 Human Element of DevOps Post
  content/blog/human_element.md
  content/blog/velocity.md
  content/legal/security.md
Labels: enhancement

#105 Calculating Change Failure Rate Blog Post
  CHANGELOG.md
  content/blog/2020-40-23-python-choices-enums.md
  content/blog/calculating_change_failure_rate_with_semver.md
  content/legal/security.md
Labels: enhancement

#108 Mean Time to Recovery Post
  content/blog/calculating_change_failure_rate.md
  content/blog/calculating_mean_time_to_recovery.md
Labels: enhancement

#110 Leaderboards & Links to Latest Blog Posts
  content/blog/calculating_change_failure_rate.md
  content/blog/calculating_mean_time_to_recovery.md
Labels: enhancement

#111 Measuring Lead Time For Change Blog Post
  content/blog/calculating_mean_time_to_recovery.md
  content/blog/measuring_lead_time_for_change.md
Labels: enhancement

#113 Measuring deployment frequency blog post
  content/blog/getting_started_with_devops.md
  content/blog/measuring_deployment_frequency.md
  content/blog/measuring_lead_time_for_change.md
  src/images/blog/Apollo-13.jpg
  src/images/blog/american_center_for_mobility.jpg
Labels: enhancement

#117 Add Github CLI blog post
  content/blog/2020-05-16-github-cli.md
Labels: content

#118 Fix broken image and typos
  content/blog/2020-05-16-github-cli.md
Labels: bug

#120 Reviewing Pull Request blog post
  content/blog/measuring_deployment_frequency.md
  content/blog/reviewing-pull-requests.md
Labels: enhancement

#122 Fixing date of blog post
  content/blog/reviewing-pull-requests.md
Labels: bug

#124 Fixing messed up bullet points
  content/blog/reviewing-pull-requests.md
Labels: bug

#126 Fixing broken link on Getting Started with DevOps page
  content/blog/getting_started_with_devops.md
Labels: bug
